[spine]
spine1 ansible_host=1.1.1.1
spine2 ansible_host=2.2.2.2

[spine:vars]
ansible_user=cumulus
ansible_password=cumulus
ansible_become=yes
ansible_become_method=sudo
ansible_connection=ssh
ansible_network_os=cumulus
